### ISSUE TITLE
Не работают обходы, вопрос

### ISSUE THREAD

**Issue by winnerbylife13** [Elllkere/misterfishdpi#1]
Попробовал misterfishdpi, потому что сколько не пробовал версий запретов (оригинальная и версии с пресетами), никакие не помогают. Проблема заключается в том, что при подключении на вайфае все работает, но при проводном, которым я очевидно пользуюсь вместо вайфая, не работает ни один способ обхода (провайдер Ростелеком, но пресеты ростелекома, которые я находил также не работают на кабельном). Я попробовал проверить блокчеком, но как можно понять, вообще не смыслю ничего в DPI и всем с этим связанным, попробовал сегодня quick блокчек и выбрал ipv4 и ipv6 вместе, в summary мне выдало следующее:

> ipv4 discord.com curl_test_http : working without bypass
> ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
> ipv4 discord.com curl_test_http3 : winws not working
> ipv6 discord.com curl_test_http : test aborted, no reason to continue. curl code 6: could not resolve host
> ipv6 discord.com curl_test_https_tls12 : test aborted, no reason to continue. curl code 6: could not resolve host
> ipv6 discord.com curl_test_http3 : test aborted, no reason to continue. curl code 6: could not resolve host
> ipv4 youtube.com curl_test_http : working without bypass
> ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=split2
> ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake --dpi-desync-repeats=5
> ipv6 youtube.com curl_test_http : test aborted, no reason to continue. curl code 6: could not resolve host
> ipv6 youtube.com curl_test_https_tls12 : test aborted, no reason to continue. curl code 6: could not resolve host
> ipv6 youtube.com curl_test_http3 : test aborted, no reason to continue. curl code 6: could not resolve host

До этого пробовал standard, только ipv4 и только discord.com:

> ipv4 discord.com curl_test_http : working without bypass
> ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
> ipv4 discord.com curl_test_http3 : winws not working

Это все было при подключении интернета к ноутбуку кабелем, на вайфае блокчек не запускал (если это как-то влияет на ситуацию..)

Возможно с этими данными можно подобрать обход или объяснить, в чем проблема заключается? Прошу помочь, если это возможно, потому что разбираюсь я в этом плохо, а пользоваться дискордом хочется :(

**Comment by Elllkere** [comment]
Я так понимаю проблема решена или случайно закрыта?

**Comment by winnerbylife13** [comment]
попробовал flowseal и на нем работает, хотя вроде раньше не работало, странно

**Comment by Elllkere** [comment]
Ну если с моим приложением не работал ни дискорд, ни ютуб то это странно, а если только ютуб то в настройках есть выбор провайдера на ростелеком, но там ростелеком снова чудит и надо снова подбирать настройки для ютуба
