### ISSUE TITLE
Дополнительный сервис - other

### ISSUE THREAD

**Issue by Katranius** [Elllkere/misterfishdpi#2]
Добавить бы надо 4-ый сервис с иконкой и своим листом, куда пользователи будут вписывать свои домены.

**Comment by Elllkere** [comment]
Это не совсем рабочая штука, т.к. для разных сервисов разные стратегии дурения, универсального нет. Можно вполне вручную добавить нужный домен в list-*.txt из доступных в папке. Я бы наверно порекомендовал добавлять в list-7tv, но можно и в ютуб\дис. Если для всех делать одну стратегию дурения, то кто то будет работать медленно, какой то домен в целом не пропустит и прочее. Можно просто предложить добавить новый сервис и желательно хотябы дать стратегии из [blockcheck](https://github.com/bol-van/zapret-win-bundle/tree/master/blockcheck) с указанием провайдера (предварительно выключить все обходы для правильной проверки)

А еще я бы порекомендовал создавать дискуссии для таких сообщений в https://github.com/Elllkere/misterfishdpi/discussions , все же этот раздел для проблем :)
